// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace Vertice.Migrations
{
    public partial class CharacterPermission : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "Permission",
                table: "CharacterModel",
                nullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Permission",
                table: "CharacterModel");
        }
    }
}
