// <auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

namespace Vertice.Migrations
{
    public partial class CreateCharacter : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "AttributeModel",
                columns: table => new
                {
                    AttributeId = table.Column<int>(nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    Strength = table.Column<int>(nullable: false),
                    Dexterity = table.Column<int>(nullable: false),
                    Constitution = table.Column<int>(nullable: false),
                    Intelligence = table.Column<int>(nullable: false),
                    Wisdom = table.Column<int>(nullable: false),
                    Charisma = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AttributeModel", x => x.AttributeId);
                });

            migrationBuilder.CreateTable(
                name: "CharacterModel",
                columns: table => new
                {
                    CharacterId = table.Column<int>(nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    OwnerID = table.Column<string>(nullable: true),
                    CharacterName = table.Column<string>(nullable: true),
                    MainAttributesAttributeId = table.Column<int>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CharacterModel", x => x.CharacterId);
                    table.ForeignKey(
                        name: "FK_CharacterModel_AttributeModel_MainAttributesAttributeId",
                        column: x => x.MainAttributesAttributeId,
                        principalTable: "AttributeModel",
                        principalColumn: "AttributeId",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_CharacterModel_MainAttributesAttributeId",
                table: "CharacterModel",
                column: "MainAttributesAttributeId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CharacterModel");

            migrationBuilder.DropTable(
                name: "AttributeModel");
        }
    }
}
