name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      working-directory: ./Vertice/Vertice/
      working-test-directory: ./Vertice/D20Tests/

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
      working-directory: ${{env.working-directory}}
    - name: Build Vertice
      run: dotnet build --configuration Release --no-restore /p:TreatWarningsAsErrors=true /warnaserror
      working-directory: ${{env.working-directory}}
    - name: Build Tests
      run: dotnet build --configuration Release --no-restore /p:TreatWarningsAsErrors=true /warnaserror
      working-directory: ${{env.working-test-directory}}
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ${{env.working-test-directory}}
